package com.ssasa6.f1fanapp.ui

data class AppStrings(
    // Nav
    val navHome: String,
    val navRaces: String,
    val navStandings: String,
    val navNews: String,
    val navMyTeam: String,
    // Home
    val pickYourTeam: String,
    val nextRaceLabel: String,
    val roundLabel: String,
    val daysLabel: String,
    val hrsLabel: String,
    val minLabel: String,
    val secLabel: String,
    val lightsOut: String,
    val titleFight: String,
    val standingsLink: String,
    val constructorsLabel: String,
    val ptsLabel: String,
    val latestLabel: String,
    val newsLink: String,
    val lapsLabel: String,
    // Races
    val season2026: String,
    val raceCalendar: String,
    val roundsDoneLabel: String,
    val winnerLabel: String,
    val nextLabel: String,
    val raceNextDate: String,
    // Standings
    val championshipLabel: String,
    val standingsTitle: String,
    val driversLabel: String,
    val leaderLabel: String,
    // Team
    val myTeamLabel: String,
    val editLabel: String,
    val drivers2026Label: String,
    val pointsLabel: String,
    val titlesLabel: String,
    val posLabel: String,
    val recentFormLabel: String,
    val last5Label: String,
    val carLabel: String,
    val powerUnitLabel: String,
    val teamPrincipalLabel: String,
    val headquartersLabel: String,
    val firstEntryLabel: String,
    // News
    val paddockLabel: String,
    val latestNewsTitle: String,
    val filterAll: String,
    val filterReports: String,
    val filterTech: String,
    val filterTeams: String,
)

val EnglishStrings = AppStrings(
    navHome = "Home", navRaces = "Races", navStandings = "Standings", navNews = "News", navMyTeam = "My Team",
    pickYourTeam = "PICK YOUR TEAM",
    nextRaceLabel = "NEXT RACE", roundLabel = "ROUND",
    daysLabel = "DAYS", hrsLabel = "HRS", minLabel = "MIN", secLabel = "SEC",
    lightsOut = "Lights out",
    titleFight = "TITLE FIGHT", standingsLink = "Standings ›",
    constructorsLabel = "CONSTRUCTORS", ptsLabel = "PTS",
    latestLabel = "LATEST", newsLink = "News ›",
    lapsLabel = "laps",
    season2026 = "2026 SEASON", raceCalendar = "RACE CALENDAR", roundsDoneLabel = "ROUNDS DONE",
    winnerLabel = "WINNER", nextLabel = "NEXT", raceNextDate = "Jul 5",
    championshipLabel = "CHAMPIONSHIP · 2026", standingsTitle = "STANDINGS",
    driversLabel = "DRIVERS", leaderLabel = "LEADER",
    myTeamLabel = "MY TEAM", editLabel = "Edit ›",
    drivers2026Label = "2026 DRIVERS", pointsLabel = "POINTS", titlesLabel = "TITLES",
    posLabel = "POS", recentFormLabel = "RECENT FORM", last5Label = "last 5",
    carLabel = "CAR · 2026",
    powerUnitLabel = "Power unit", teamPrincipalLabel = "Team principal",
    headquartersLabel = "Headquarters", firstEntryLabel = "First entry",
    paddockLabel = "PADDOCK · 2026", latestNewsTitle = "LATEST NEWS",
    filterAll = "All", filterReports = "Reports", filterTech = "Tech", filterTeams = "Teams",
)

val KoreanStrings = AppStrings(
    navHome = "홈", navRaces = "레이스", navStandings = "순위", navNews = "뉴스", navMyTeam = "내 팀",
    pickYourTeam = "팀 선택",
    nextRaceLabel = "다음 레이스", roundLabel = "라운드",
    daysLabel = "일", hrsLabel = "시", minLabel = "분", secLabel = "초",
    lightsOut = "출발",
    titleFight = "챔피언십 순위", standingsLink = "순위 ›",
    constructorsLabel = "컨스트럭터", ptsLabel = "포인트",
    latestLabel = "최신", newsLink = "뉴스 ›",
    lapsLabel = "랩",
    season2026 = "2026 시즌", raceCalendar = "레이스 캘린더", roundsDoneLabel = "완료된 라운드",
    winnerLabel = "우승자", nextLabel = "다음", raceNextDate = "7월 5일",
    championshipLabel = "챔피언십 · 2026", standingsTitle = "순위",
    driversLabel = "드라이버", leaderLabel = "선두",
    myTeamLabel = "내 팀", editLabel = "편집 ›",
    drivers2026Label = "2026 드라이버", pointsLabel = "포인트", titlesLabel = "타이틀",
    posLabel = "순위", recentFormLabel = "최근 성적", last5Label = "최근 5경기",
    carLabel = "머신 · 2026",
    powerUnitLabel = "파워 유닛", teamPrincipalLabel = "팀 대표",
    headquartersLabel = "본부", firstEntryLabel = "최초 참가",
    paddockLabel = "패독 · 2026", latestNewsTitle = "최신 뉴스",
    filterAll = "전체", filterReports = "리포트", filterTech = "기술", filterTeams = "팀",
)

fun appStrings(isKorean: Boolean): AppStrings = if (isKorean) KoreanStrings else EnglishStrings
